#!/bin/sh

cd /tmp 

curl http://www.freedesktop.org/software/systemd/systemd-${SYSTEMD_VERSION}.tar.xz | tar -xJ 

cd systemd-${SYSTEMD_VERSION} 

mkdir /tmp/build

./configure --prefix=/tmp/build/usr 

make && make install 

cd /tmp/build

tar -Jcf /artifacts/systemd-${SYSTEMD_VERSION}-usr.tar.xz usr


